### ISSUE TITLE
how to install this?

### ISSUE THREAD

**Issue by Crucizer** [andrewpavlenko/dotfiles#1]
I installed awesomewm but I have no idea how to replicate your theme and stuff to my wm, can you help me?

**Comment by andrewpavlenko** [comment]
Sorry for a so unusefull readme. I didn't guess that anyone will be interested in replicating my configs. To make things work you need to copy `awesome` folder from my repository to `~/.config/` folder on your system and then install required fonts. [This](https://github.com/stephenhutchings/typicons.font) font is required for taglist widget and also lock screen requires custom fonts that can be downloaded from google fonts. I suppose that you have some skills in configuring awesomewm for fix possible issues to make your setup work.
